### ISSUE TITLE
Recommend promise event over beforeIndex hook in apostrophe-search

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-open-museum#22]
https://github.com/apostrophecms/apostrophe-demo-2018/blob/354fe1065fbd85e1ea4ee8e565036b809cbe292b/lib/modules/apostrophe-search/index.js#L13

https://apostrophecms.org/docs/events.html

**Comment by stuartromanek** [comment]
Doesn't look like doc-type-manager/custom-pages `beforeIndex` is supported. Testing this came up nil. closing for now

**Comment by boutell** [comment]
Promise events are a big win where we used to use `callAll`. But for lifecycle methods of a single module, we don't have them thus far, and I'm not sure we will because in 3.x, with async/await, it is easier to follow the `super` pattern successfully and events do add some overhead as compared to plain ol' methods.

**Comment by boutell** [comment]
If there are any instances of `pageBeforeSend`, etc., those should definitely become promise event handlers.

**Comment by austinstarin** [comment]
Thanks for the clarification @tom, got mixed up there...
